### ISSUE TITLE
[Bug]: AnyKernel3 zip issues

### ISSUE THREAD

**Issue by erffy** [dabao1955/kernel_build_action#116]
### CheckBox

- [x] I have searched the issue list and found no similar issues.
- [x] I use the official action instead of someone else's
- [x] I have read the FAQ section in README.md

### Configuration
```yml
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/fjrXTR/v1llx-gki-5.10
          kernel-branch: villhaze-new
          config: gki_defconfig
          arch: arm64
          ksu: true
          ksu-other: true
          ksu-url: https://github.com/KernelSU-Next/KernelSU-Next
          ksu-version: next
          aosp-gcc: true
          anykernel3: true
          anykernel3-url: https://github.com/osm0sis/AnyKernel3
          aosp-clang: true
          android-version: 12
          release: true
          access-token: ${{ secrets.GH_TOKEN }}
          ccache: true
          aosp-clang-version: r416183b
```

### Describe the bug

I'm trying to get the kernel compiled with AnyKernel3 but the zip format is given in the wrong format.

### Screenshots

![Image](https://github.com/user-attachments/assets/0f579b0f-abce-46fc-823d-716c3296d04e)

### How to reproduce

1. Use this action to build kernel with AnyKernel3 enabled

### Expected behavior

Compiled kernel with AnyKernel3
