### ISSUE TITLE
[Bug]: AnyKernel3 invalid path

### ISSUE THREAD

**Issue by erffy** [dabao1955/kernel_build_action#118]
### CheckBox

- [x] I have searched the issue list and found no similar issues.
- [x] I use the official action instead of someone else's
- [x] I have read the FAQ section in README.md

### Configuration

```yaml
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          access-token: ${{ secrets.GH_TOKEN }}
          android-version: 12
          anykernel3: true
          anykernel3-url: https://github.com/osm0sis/AnyKernel3
          aosp-clang: true
          aosp-clang-version: r416183b
          aosp-gcc: true
          arch: arm64
          ccache: true
          config: gki_defconfig
          kernel-branch: villhaze-new
          kernel-url: https://github.com/fjrXTR/v1llx-gki-5.10
          ksu: true
          ksu-other: true
          ksu-url: https://github.com/KernelSU-Next/KernelSU-Next
          ksu-version: next
          release: true
```

### Describe the bug

Wrong path provided for mv

### Screenshots

![Image](https://github.com/user-attachments/assets/4afe7d38-8386-4ee6-9882-4c5870dabe0b)
