### ISSUE TITLE
[Bug]: OrangeFox Recovery  "Invalid zip file format"

### ISSUE THREAD

**Issue by erffy** [dabao1955/kernel_build_action#120]
### CheckBox

- [x] I have searched the issue list and found no similar issues.
- [x] I use the official action instead of someone else's
- [x] I have read the FAQ section in README.md

### Configuration

```yaml
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          access-token: ${{ secrets.GH_TOKEN }}
          android-version: 12
          anykernel3: true
          aosp-clang: true
          aosp-clang-version: r416183b
          aosp-gcc: true
          arch: arm64
          ccache: true
          config: gki_defconfig
          kernel-branch: android12-5.10
          kernel-url: https://github.com/Shirayuki39/android_kernel_common-5.10-android12
          ksu: true
          ksu-other: true
          ksu-url: https://github.com/KernelSU-Next/KernelSU-Next
          ksu-version: next
          release: true
```

### Describe the bug

OrangeFox says 'Invalid zip file format'

### Screenshots

![Image](https://github.com/user-attachments/assets/f401c832-6c15-4917-8aee-f1b0a6909e67)

### How to reproduce

1. Try to flash zip file in OrangeFox Recovery

### Expected behavior

Flash zip file successfully

### Additional context

In screenshot, the top one is a different GKI AnyKernel3 zip and the bottom one is the AnyKernel3 zip made by creating this action, the top one flashes fine while the bottom one gives error.

I'm getting tired of kernels...
